-- Migration 0008: Fix remaining schema drift
-- Generated by schema verification tool
-- Note: Foreign key constraints skipped to avoid issues with existing data

-- ============================================================================
-- TASKS TABLE: Add missing column
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'tasks' AND column_name = 'custom_status_id') THEN
        ALTER TABLE tasks ADD COLUMN custom_status_id INTEGER;
    END IF;
END $$;

-- ============================================================================
-- STAKEHOLDERS TABLE: Add missing timestamp columns
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'stakeholders' AND column_name = 'created_at') THEN
        ALTER TABLE stakeholders ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'stakeholders' AND column_name = 'updated_at') THEN
        ALTER TABLE stakeholders ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
    END IF;
END $$;

-- ============================================================================
-- RISKS TABLE: Add missing columns
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'response_strategy') THEN
        ALTER TABLE risks ADD COLUMN response_strategy VARCHAR(50);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'cost_impact') THEN
        ALTER TABLE risks ADD COLUMN cost_impact NUMERIC;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'schedule_impact') THEN
        ALTER TABLE risks ADD COLUMN schedule_impact INTEGER;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'risk_exposure') THEN
        ALTER TABLE risks ADD COLUMN risk_exposure NUMERIC;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'contingency_reserve') THEN
        ALTER TABLE risks ADD COLUMN contingency_reserve NUMERIC;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'assigned_to') THEN
        ALTER TABLE risks ADD COLUMN assigned_to INTEGER;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'target_resolution_date') THEN
        ALTER TABLE risks ADD COLUMN target_resolution_date TIMESTAMP;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'created_at') THEN
        ALTER TABLE risks ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'risks' AND column_name = 'updated_at') THEN
        ALTER TABLE risks ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
    END IF;
END $$;

-- ============================================================================
-- ISSUES TABLE: Add missing columns
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'impact_cost') THEN
        ALTER TABLE issues ADD COLUMN impact_cost NUMERIC;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'impact_schedule') THEN
        ALTER TABLE issues ADD COLUMN impact_schedule INTEGER;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'impact_quality') THEN
        ALTER TABLE issues ADD COLUMN impact_quality VARCHAR(50);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'impact_safety') THEN
        ALTER TABLE issues ADD COLUMN impact_safety VARCHAR(50);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'discipline') THEN
        ALTER TABLE issues ADD COLUMN discipline VARCHAR(50);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'escalation_level') THEN
        ALTER TABLE issues ADD COLUMN escalation_level INTEGER DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'target_resolution_date') THEN
        ALTER TABLE issues ADD COLUMN target_resolution_date TIMESTAMP;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'created_at') THEN
        ALTER TABLE issues ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'issues' AND column_name = 'updated_at') THEN
        ALTER TABLE issues ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
    END IF;
END $$;

-- ============================================================================
-- CHANGE_REQUESTS TABLE: Create if not exists
-- ============================================================================

CREATE TABLE IF NOT EXISTS change_requests (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    change_type VARCHAR(50),
    priority VARCHAR(20) DEFAULT 'medium',
    status VARCHAR(50) DEFAULT 'pending',
    requested_by INTEGER,
    approved_by INTEGER,
    impact_scope TEXT,
    impact_schedule INTEGER,
    impact_cost NUMERIC,
    justification TEXT,
    implementation_plan TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_change_requests_project_id ON change_requests(project_id);
CREATE INDEX IF NOT EXISTS idx_change_requests_status ON change_requests(status);

-- ============================================================================
-- PROJECT_STATUSES TABLE: Add missing columns
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'project_statuses' AND column_name = 'code') THEN
        ALTER TABLE project_statuses ADD COLUMN code VARCHAR(50);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'project_statuses' AND column_name = 'order') THEN
        ALTER TABLE project_statuses ADD COLUMN "order" INTEGER DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'project_statuses' AND column_name = 'is_active') THEN
        ALTER TABLE project_statuses ADD COLUMN is_active BOOLEAN DEFAULT true;
    END IF;
END $$;
